"use client";

import React from "react";
import { Inter } from "next/font/google";
import Container from "@mui/material/Container";
import { AppBar, CssBaseline, IconButton, Toolbar } from "@mui/material";
import Typography from "@mui/material/Typography";
import GitBranch from "@assets/icons/GitBranch";
import { QueryClientProvider } from "@tanstack/react-query";
import { queryClient } from "@api/config";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={ inter.className }>
        <QueryClientProvider client={ queryClient }>
          <CssBaseline />

          <AppBar position="static" color="primary" enableColorOnDark>
            <Toolbar>
              <IconButton edge="start" color="inherit" aria-label="menu" sx={ { mr: 2 } }>
                <GitBranch />
              </IconButton>

              <Typography variant="h6" noWrap component="div" sx={ { flexGrow: 1 } }>
                Almosafer
              </Typography>
            </Toolbar>
          </AppBar>

          <Container sx={ { my: "5rem" } }>
            { children }
          </Container>
        </QueryClientProvider>
      </body>
    </html>
  );
}
